# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# 站点基础设置
locale                   : "zh-CN"
title                    : "Chen Zhenli | 个人主页"
title_separator          : "-"
name                     : "Chen Zhenli"
description              : "Fudan University | AI Enthusiast"
url                      : "https://zhenlichen.github.io"
baseurl                  : ""
repository               : "zhenlichen/zhenlichen.github.io"
teaser                   : 

# 侧边栏作者信息
author:
  name             : "Chen Zhenli"
  avatar           : "profile.jpg" # 确保 images/ 文件夹下有这个图，没有就先留着
  bio              : "Fudan University | 捣鼓 AI 的开发者"
  location         : "Shanghai, China"
  email            : "242101100013@m.fudan.edu.cn"
  github           : "ZhenliChen"
  # linkedin       : "your-username" # 有的话就把 # 去掉并填上

# 读取与转换设置
include:
  - .htaccess
  - _pages
  - files
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - node_modules
  - package.json
  - Gruntfile.js
  - gulpfile.js
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# 核心引擎 (不要动这里)
markdown: kramdown
highlighter: rouge
collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/

# 默认布局设置
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true

# 插件
gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from

# 只有这个设为 master 或 main 才能正常部署
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
